### ISSUE TITLE
crashing problems from parsing and resolving

### ISSUE THREAD

**Issue by jeffallen** [jschaf/bibtex#1]
Hello, thanks for this, it's right what I need, right when I need it.

I tried to parse a huge list of entries, and I got a panic from ResolveAuthors in the case where there are {} inside of an author value. PR #2 shows the failing input.

I don't understand enough about the AST to fix it myself yet.

**Comment by jeffallen** [comment]
I found a related problem with commas in author names, and included a second commit with a test and some ideas on how to fix these. Hope this is helpful.

**Comment by jeffallen** [comment]
Moving on through my list of bibtex entries, I found one which causes the parser to go into an infinite loop and I write a unite test for it. It is unclear how dollar should be handled, when it is not starting a TeX formula. But it should not be possible to put the parser into an infinite look anyway. :(

**Comment by jschaf** [comment]
Hi there, glad you found it useful!

>  I found one which causes the parser to go into an infinite loop

Perfect, can you post it or a representative example here?

> It is unclear how dollar should be handled

Turns about Bibtex is pretty underspecified. Whatever biblatex does is probably the right answer.

> it should not be possible to put the parser into an infinite look anyway

Agreed. I've been meaning to try fuzzing. It'd be good for this.

**Comment by jeffallen** [comment]
The $ problem is actually 2 problems. An unterminated math expression will hang the parser. And backslash to escape characters is not implemented yet in the scanner. The characters that need to be escaped are listed in the end of this page: http://www.bibtex.org/SpecialSymbols/

**Comment by jeffallen** [comment]
The escaping works now, but the parser can still be hung with unterminated things.

**Comment by jschaf** [comment]
https://github.com/jschaf/bibtex/commit/a17d7107bf00be5774b47a8a7820a48eabbc3a6d should fix some of the issues in the tokenizer.

- Allow escaped chars like dollar signs.
- Allow trailing commas after bib declarations

It doesn't fix the author parsing or unterminated math hanging the parser. I'll take a look at those.

**Comment by jschaf** [comment]
Endless loop fixed in https://github.com/jschaf/bibtex/commit/c0bf8bf75bce222408aca120fff9d7a5794cab6b
