### ISSUE TITLE
What is the right way to use the new API?

### ISSUE THREAD

**Issue by GreatDanton** [jschaf/bibtex#4]
I tried to use the latest master branch, and with some trial and error I came up with the following parsing code:

```go
package parsing

import (
	"fmt"
	"github.com/jschaf/bibtex"
	"strings"
	"testing"
)

func Test_bibtex_parser(t *testing.T) {
	input := `
    @book{greub2012linear,
      title={Linear algebra},
      author={Greub, Werner H},
      volume={23},
      year={2012},
      publisher={Springer Science \& Business Media}
    }

    @inproceedings{francese2015model,
      title={Model-driven development for multi-platform mobile applications},
      author={Francese, Rita and Risi, Michele and Scanniello, Giuseppe and Tortora, Genoveffa},
      booktitle={Product-Focused Software Process Improvement: 16th International Conference, PROFES 2015, Bolzano, Italy, December 2-4, 2015, Proceedings 16},
      pages={61--67},
      year={2015},
      organization={Springer}
    }
`
	bibParser := bibtex.New()
	parsedAst, err := bibParser.Parse(strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	entries, err := bibParser.Resolve(parsedAst)
	if err != nil {
		t.Fatal(err)
	}

	for _, e := range entries {
		// type: (Article, etc...)
		sourceType := e.Type
		fmt.Println(sourceType)

		// key: (this is our id to reference)
		entryId := e.Key
		fmt.Println(entryId)

		for key, val := range e.Tags {
			fmt.Println(key, ": ", input[val.Pos():val.End()])
		}
		fmt.Println("")
		fmt.Println("-------------------------")
		fmt.Println("")
	}
```

The output, however, is missing characters (check author, title, volume, year fields):

```
book
greub2012linear
year :  2
publisher :  Springer Science \& Business M
title :  Linear a
author :  Greub, Werner H
volume :  2

-------------------------

inproceedings
francese2015model
title :  Model-driven development for multi-platform mobile a
author :  Francese, Rita and Risi, Michele and Scanniello, Giuseppe and Tortora, G
booktitle :  Product-Focused Software Process Improvement: 16th International Conference, PROFES 2015, Bolzano, Italy, December 2-4, 2015, Proceedings 1
pages :  6
year :  2
organization :  S
```

Am I doing something wrong here, or is the master branch currently broken?

**Comment by jschaf** [comment]
Hello, didn't realize anyone had stumbled onto my little library.

I just checked out the code and made sure all the tests pass. I added the linear algebra book as a new test case.

This line is probably the culprit:

```
input[val.Pos():val.End()]
```

The library returns the start of the last token, not the end, for `val.End()`.

You can use something like what the tests use to render everything:

```
			bib := bibtex.New(
				bibtex.WithResolvers(
					bibtex.NewAuthorResolver("author"),
					bibtex.ResolverFunc(bibtex.SimplifyEscapedTextResolver),
					bibtex.NewRenderParsedTextResolver(),
				))
```

**Comment by GreatDanton** [comment]
Thanks for the explanation, but I am still wondering what is the correct way to extract the string from the field.

Say I have:
```
entries, _ := bib.Resolve(file)
for _, e := range entries {
    titleNode := e.Tags[bibtex.FieldBookTitle]
    // there is no title string getter and titleNode.End() returns start of the end token
    // so I can't use it on the input string.
}
```


Edit:
I guess I can cast the ast.Expr node as:
```
switch t := title(.type) {
 case *ast.Text:
   fmt.Println(t.Value)
default:
   // do nothing
}
```

**Comment by jschaf** [comment]
> Thanks for the explanation, but I am still wondering what is the correct way to extract the string from the field.

You have to traverse the AST.

For rendering, we really just want a string. That's where NewRenderParsedTextResolver helps. It modifies the AST in place to convert tag fields into an `ast.Text` field. The `ast.Text` field holds a plain string.

Authors are a bit more complicated and rendering is application specific, so the individual parts of an author name, like last and first name, are converted to `ast.Text`, but the AST keeps the `ast.Authors` node.

 I added a complete example to render your example in https://github.com/jschaf/bibtex/blob/master/bibtex_test.go#L115.
