### ISSUE TITLE
Error on parsing Umlaute

### ISSUE THREAD

**Issue by andresterba** [jschaf/bibtex#5]
First of all, thank you for this lib!

I hit a problem with an export from [acm](https://dl.acm.org/).
No expert in bibtex, but they seem to export `ä` differently then your test data.

The error I get is `expected command name to only contain ascii letters, got "\""`.
And the problem is the `authors` field and the value `H\"{a}berle`.

Here is an extract from the input I'm using:

```
@inproceedings{10.1145/3426744.3431327,
author = {Lindner, Steffen and Merling, Daniel and H\"{a}berle, Marco and Menth, Michael},
title = {P4-Protect: 1+1 Path Protection for P4},
...
```

**Comment by jschaf** [comment]
Are you sure that's valid BibTex? This Stackoverflow question https://tex.stackexchange.com/a/57745, states that you must wrap accented characters in braces:

> Why are the ordinary methods of entering these characters in a LaTeX document -- say, `\"{a}` or `\"a`, let alone ä -- not quite right for BibTeX?

```
    author = "Anna H\"{a}user",
```

That said, if it's common enough, it might be worth adding support.

**Comment by andresterba** [comment]
> Are you sure that's valid BibTex?

I don't know, but based on the stackoverflow answers it doesn't look so.

My examples is the BibTex export of [this paper](Are you sure that's valid BibTex?), which looks like this:

```
@inproceedings{10.1145/3426744.3431327,
author = {Lindner, Steffen and Merling, Daniel and H\"{a}berle, Marco and Menth, Michael},
title = {P4-Protect: 1+1 Path Protection for P4},
year = {2020},
isbn = {9781450381819},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/3426744.3431327},
...
}
```

I've checked another source of that author and the export is again in the same format.
[Source](https://dl.acm.org/doi/10.1016/j.jnca.2022.103561):

```
@article{10.1016/j.jnca.2022.103561,
author = {Hauser, Frederik and H\"{a}berle, Marco and Merling, Daniel and Lindner, Steffen and Gurevich, Vladimir and Zeiger, Florian and Frank, Reinhard and Menth, Michael},
title = {A survey on data plane programming with P4: Fundamentals, advances, and applied research},
year = {2023},
issue_date = {Mar 2023},
publisher = {Academic Press Ltd.},
...
```

So there are two things we could try:
1. Ask ACM why they export umlaute like this. (I'm happy to ask them, but not sure if this is something they are going to care about.)
2. Handle the case in the lib.


And thank you for taking a look into this!

**Comment by jschaf** [comment]
I added support for both types of accenting. I probably should have defined it as text macro but it felt different enough to special-case it.

> Ask ACM why they export umlaute like this.

If you don't mind, it'd be worth letting them know since it looks like a bug.
